env: edge_cloud1
env-config:
  auction_type: first-price
  avg_resource_capacity:
    0:
    - 6
    - 6
    - 6
    1:
    - 6
    - 6
    - 6
    2:
    - 4
    - 4
    - 4
  avg_unit_cost:
    0:
    - 2
    - 2
    - 2
    1:
    - 2
    - 2
    - 2
    2:
    - 3
    - 3
    - 3
  cooperative: false
  duration: 7
  history_len: 4
  n_actions: 5
  n_nodes: 3
  n_tasks_in_total: 42
  n_tasks_to_allocate: 40
  num_agents: 3
  random_seed: false
  record_history: false
  seed: 2201
  usage_time_ub: 3
  verbose: false
name: 5-actions_first-price_no-history_revenue
samples: 1
stop:
  timesteps_total: 50000
trainer: PPO
trainer-config:
  batch_mode: complete_episodes
  entropy_coeff: 0.0
  framework: torch
  lambda: 1.0
  lr:
    gridsearch:
    - 0.0001
    - 0.001
  model:
    custom_model: FCModel
    custom_model_config:
      layers:
        gridsearch:
        - - 256
          - 256
  num_gpus: 0
  num_workers: 20
  observation_filter:
    gridsearch:
    - MeanStdFilter
  seed: 9325
  sgd_minibatch_size:
    gridsearch:
    - 64
    - 128
  synchronize_filters: true
  train_batch_size:
    gridsearch:
    - 3000
    - 4000
