name: edge_cloud_independent_ppo_one-node_2-actions_env-3
# https://docs.ray.io/en/master/rllib-algorithms.html
# rllib algorithms and their configs
# common hyperparameters: https://docs.ray.io/en/master/rllib-training.html#common-parameters

#env: edge_cloud
env: edge_cloud1

env-config:
  n_nodes: 1
  num_agents: 1
  n_tasks_in_total: 22
  n_tasks_to_allocate: 20
  duration: 10
  usage_time_ub: 3
  seed: 124
  random_seed: False

# agents should learn that low-value tasks should not be allocated to node 0
  avg_resource_capacity: { 0: [6, 6, 6]}
  avg_unit_cost: { 0: [ 3, 3, 3 ]}
#  verbose: True
  verbose: False
#  "log_level": "DEBUG"
  record_history: False
  history_len: 3
  cooperative: True
  n_actions: 2
  auction_type: 'first-price'



trainer: PPO
trainer-config:
  framework: torch
#  num_envs_per_worker: 1
  # number of workers for collecting samples with.
  num_workers: 18
#  num_workers: 18  # for run locally
#  num_workers: 1  # used when checking the log
  num_gpus: 1
#  num_gpus: 0  # for run locally
#  # set a seed_value value for each worker as well as for the environment
  seed: 124
  # Element-wise observation filter, either "NoFilter" or "MeanStdFilter".
  # https://gitmemory.com/issue/ray-project/ray/9399/683323479
  # https://intellabs.github.io/coach/components/filters/input_filters.html
  "observation_filter": "MeanStdFilter"
#  "observation_filter": "NoFilter"
  # Whether to synchronize the statistics of remote filters.
  "synchronize_filters": True

  # Model config
  model:
    custom_model: FCModel
    custom_model_config:
      layers:
#        gridsearch: [[64, 64], [128, 128], [256, 256], [512, 512], [64, 64, 64], [128, 128, 128], [256, 256, 256], [512, 512, 512]]
        gridsearch: [[256, 256]]

  # Trainer parameters
  lr:
    gridsearch: [0.0001, 0.001]
#    gridsearch: [0.001]
  lambda: 1.0
  entropy_coeff: 0.0
  batch_mode: "complete_episodes"
#  rollout_fragment_length: 220
  # The size of each SGD epoch = Size of Training Set
  train_batch_size:
    gridsearch: [3000, 4000, 5000]
#    gridsearch: [3000]
  # The minibatch size within each epoch.
  # This number of samples will be worked through before updating the model's
  #    internal parameters.
#  sgd_minibatch_size: 128


stop:
  timesteps_total: 15_0000
#  timesteps_total: 4_0000

#samples: 4
