name: 5-actions_first-price_no-history_revenue
# https://docs.ray.io/en/master/rllib-algorithms.html
# rllib algorithms and their configs
# common hyperparameters: https://docs.ray.io/en/master/rllib-training.html#common-parameters

#env: edge_cloud
env: edge_cloud1

env-config:
  n_nodes: 3
  num_agents: 3
  n_tasks_in_total: 42
  n_tasks_to_allocate: 40
  duration: 7
  usage_time_ub: 3
  seed: 124
  random_seed: True

# agents should learn that low-value tasks should not be allocated to node 0
  avg_resource_capacity: { 0: [ 6, 6, 6], 1: [6, 6, 6], 2:[4, 4, 4]}
  avg_unit_cost: { 0: [ 2, 2, 2], 1:[2, 2, 2], 2:[5, 5, 5]}
#  verbose: True
  verbose: False
#  "log_level": "DEBUG"
#  record_history: True
  record_history: False
  history_len: 4
  cooperative: False
  n_actions: 5
  auction_type: 'first-price'
#  auction_type: 'second-price'


trainer: PPO
trainer-config:
  framework: torch
  # number of workers for collecting samples with.
  num_workers: 38 # use 6 cores out of 8 CPU cores
  num_gpus: 2
#  # set a seed_value value for each worker as well as for the environment
  seed: 124
  # Element-wise observation filter, either "NoFilter" or "MeanStdFilter".
  # https://gitmemory.com/issue/ray-project/ray/9399/683323479
  # https://intellabs.github.io/coach/components/filters/input_filters.html
  "observation_filter": "MeanStdFilter"
  # Whether to synchronize the statistics of remote filters.
  "synchronize_filters": True

  # Model config
  model:
    custom_model: FCModel
    custom_model_config:
      layers:
        gridsearch: [[256, 256]]
#        gridsearch: [[256, 256], [256, 256, 256]]

  # Trainer parameters
  lr:
     gridsearch: [0.001]
#    gridsearch: [0.0001, 0.001]
  lambda: 1.0
  entropy_coeff: 0.0
  batch_mode: "complete_episodes"
#  rollout_fragment_length: 220
  # The size of each SGD epoch = Size of Training Set
  train_batch_size:
    gridsearch: [3000]
#    gridsearch: [3000, 4000]
  # The minibatch size within each epoch.
  # This number of samples will be worked through before updating the model's
  #    internal parameters.
  sgd_minibatch_size: 128


stop:
#  timesteps_total: 10_0000
  timesteps_total: 4_0000

# how many trials to run for each hyperparameter combinations
samples: 1
